name: Release

on:
  release:
    types: [published]

jobs:
  release_zip:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create zip file
        run: |
          cd custom_components/antra-bms-monitor
          zip -r ../../antra-bms-monitor.zip .

      - name: Upload zip to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            antra-bms-monitor.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}